### ISSUE TITLE
404 Not found for http://lavis.cs.hs-rm.de/storage/german-legal-sentences/GermanLegalSentences_v0.0.2.zip

### ISSUE THREAD

**Issue by jsektkuehler** [lavis-nlp/german_legal_sentences#1]
Hi folks,

Could you kindly check the dataset link, i get a 404 error.

"Not Found
The requested URL was not found on this server."

Kind regards,
Jonathan

**Comment by mwrzalik** [comment]
Hi Jonathan,

thanks for reporting the 404 error.
 
The error is due to a infrastructure change. The download will probably be fixed within the next few days.

Cheers,
Marco

EDIT: It should work now. Please confirm if it does.

**Comment by jsektkuehler** [comment]
It does, thanks a lot!
